apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: heo6rwok2-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/heo6rwok2-java-springboot-gitops